#!/bin/bash
IMAGE_NAME='robot-docker'
VOLUME_NAME='robot-docker-volume'

docker build -t $IMAGE_NAME .
build=$!
wait $build
docker run -d --name $VOLUME_NAME -v $(pwd):/robot --shm-size=1024m $IMAGE_NAME:latest
volume=$!
wait $volume
